Appsec_222360C/ViewModels/Login.cs
using System.ComponentModel.DataAnnotations;

namespace Appsec_222360C.ViewModels
{
    public class Login
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        public bool RememberMe { get; set; }
    }
}

Appsec_222360C/ViewModels/Register.cs
using System.ComponentModel.DataAnnotations;

namespace Appsec_222360C.ViewModels
{
    public class Register
    {
        [Required]
        [DataType(DataType.Text)]
        public string firstName { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string lastName { get; set; }

        [Required]
        public string gender { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string nric { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Compare(nameof(Password), ErrorMessage = "Password and confirmation password does not match")]
        public string ConfirmPassword { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime dateOfBirth { get; set; }

        [Required]
        [DataType(DataType.Upload)]
        public string resume { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string whoAmI { get; set; }
    }
}

Appsec_222360C/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Appsec_222360C.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Appsec_222360C/Pages/Home.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;
using Microsoft.AspNetCore.DataProtection;
using Appsec_222360C.Model;

namespace Appsec_222360C.Pages
{
    public class HomeModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public HomeModel(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }

        public ApplicationUser currentUser { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            var user = await _userManager.GetUserAsync(User);

            if (user != null)
            {
                var dataProtectionProvider = DataProtectionProvider.Create("EncryptData");
                var protector = dataProtectionProvider.CreateProtector("My Secret Key");
                user.nric = protector.Unprotect(user.nric);
                currentUser = user;

                return Page();
            }

            return RedirectToPage("/Login");
        }
    }
}

Appsec_222360C/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Appsec_222360C.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Appsec_222360C/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Appsec_222360C.ViewModels;
using Appsec_222360C.Model;
using Microsoft.AspNetCore.Identity;

namespace Appsec_222360C.Pages
{
    public class LoginModel : PageModel
    {

        [BindProperty]
        public Login LModel { get; set; }

        private readonly SignInManager<ApplicationUser> signInManager;

        public LoginModel(SignInManager<ApplicationUser> signInManager)
        {
            this.signInManager = signInManager;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var identityResult = await signInManager.PasswordSignInAsync(LModel.Email, LModel.Password,
                LModel.RememberMe, false);
                if (identityResult.Succeeded)
                {
                    return RedirectToPage("Index");
                }
                ModelState.AddModelError("", "Username or Password incorrect");
            }
            return Page();
        }
    }
}

Appsec_222360C/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Appsec_222360C.Model;

namespace Appsec_222360C.Pages
{
    public class LogoutModel : PageModel
    {

        private readonly SignInManager<ApplicationUser> signInManager;

        public LogoutModel(SignInManager<ApplicationUser> signInManager)
        {
            this.signInManager = signInManager;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await signInManager.SignOutAsync();
            return RedirectToPage("Login");
        }

        public async Task<IActionResult> OnPostDontLogoutAsync()
        {
            return RedirectToPage("Index");
        }
    }
}

Appsec_222360C/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Appsec_222360C.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Appsec_222360C/Pages/Register.cshtml.cs
using Appsec_222360C.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.DataProtection;
using Appsec_222360C.Model;

namespace Appsec_222360C.Pages
{

    public class RegisterModel : PageModel
    {

        private UserManager<ApplicationUser> userManager { get; }
        private SignInManager<ApplicationUser> signInManager { get; }
        [BindProperty]
        public Register RModel { get; set; }
        public RegisterModel(UserManager<ApplicationUser> userManager,
        SignInManager<ApplicationUser> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var dataProtectionProvider = DataProtectionProvider.Create("EncryptData");
                var protector = dataProtectionProvider.CreateProtector("My Secret Key");
                var user = new ApplicationUser()
                {
                    firstName = RModel.firstName,
                    lastName = RModel.lastName,
                    UserName = RModel.Email,
                    Email = RModel.Email,
                    gender = RModel.gender,
                    nric = protector.Protect(RModel.nric),
                    dateOfBirth = RModel.dateOfBirth,
                    whoAmI = RModel.whoAmI,
                    resume = RModel.resume,
                };
                var result = await userManager.CreateAsync(user, RModel.Password);
                if (result.Succeeded)
                {
                    await signInManager.SignInAsync(user, false);
                    return RedirectToPage("Index");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return Page();
        }
    }
}

Appsec_222360C/Pages/Home.cshtml
@page
@model Appsec_222360C.Pages.HomeModel
@{
}



<div class="text-center">

    @if (Model.currentUser != null)
    {
        <h2>User Details</h2>
        <p>First Name: @Model.currentUser.firstName</p>
        <p>Last Name: @Model.currentUser.lastName</p>
        <p>Gender: @Model.currentUser.gender</p>
        <p>NRIC: @Model.currentUser.nric</p>
        <p>Date of Birth: @Model.currentUser.dateOfBirth</p>
        <p>Resume: @Model.currentUser.resume</p>
        <p>Who Am I: @Model.currentUser.whoAmI</p>
    }
</div>
S

Appsec_222360C/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Appsec_222360C/Pages/Login.cshtml
@page
@model Appsec_222360C.Pages.LoginModel
@{
}

<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-lg-4">
            <h1 class="mb-3">Login</h1>

            <form method="post">
                <div class="mb-3">
                    <label class="form-label" asp-for="LModel.Email">Email Address</label>
                    <input type="text" asp-for="LModel.Email" class="form-control" />
                    <span asp-validation-for="LModel.Email" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="LModel.Password">Password</label>
                    <input type="password" asp-for="LModel.Password" class="form-control" />
                    <span asp-validation-for="LModel.Password" class="text-danger"></span>
                </div>

                <div class="mb-3 form-check">
                    <input type="checkbox" asp-for="LModel.RememberMe" class="form-check-input" />
                    <label class="form-check-label" asp-for="LModel.RememberMe">Remember Me?</label>
                </div>

                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
            </form>
        </div>
    </div>
</div>

Appsec_222360C/Pages/Logout.cshtml
@page
@model Appsec_222360C.Pages.LogoutModel
@{
}

<form method="post">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-12 col-lg-4">
                <p>Are you sure you want to log out?</p>
                <p>
                    <button class="btn btn-primary" asp-page-handler="Logout">Yes</button>
                    <button class="btn btn-light ml-5 border-dark" asp-page-handler="DontLogout">No</button>
                </p>
            </div>
        </div>
    </div>
</form>

Appsec_222360C/Pages/Register.cshtml
@page
@model Appsec_222360C.Pages.RegisterModel
@{
}

<div class="container mt-5">

    <div class="row justify-content-center align-items-center">

        <div class="col-sm-12 col-md-12 col-lg-4">
            <h1 class="mb-3">Register for Ace Job Agency</h1>

            <form method="post">
                <div asp-validation-summary="All" class="text-danger"></div>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.firstName">First Name</label>
                    <input type="text" asp-for="RModel.firstName" class="form-control" />
                    <span asp-validation-for="RModel.firstName" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.lastName">Last Name</label>
                    <input type="text" asp-for="RModel.lastName" class="form-control" />
                    <span asp-validation-for="RModel.lastName" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.gender">Gender</label>
                    <div class="mb-3">
                        <input type="radio" id="male" value="Male" asp-for="RModel.gender" class="form-check-input" />
                        <label class="form-check-label" for="male">Male</label>
                    </div>

                    <div class="mb-3">
                        <input type="radio" id="female" value="Female" asp-for="RModel.gender" class="form-check-input" />
                        <label class="form-check-label" for="female">Female</label>
                    </div>

                    <span asp-validaton-for="RModel.gender" class="text-danger"></span>

                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.nric">NRIC</label>
                    <input type="text" asp-for="RModel.nric" class="form-control" />
                    <span asp-validation-for="RModel.nric" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.dateOfBirth">Date of Birth</label>
                    <input type="date" asp-for="RModel.dateOfBirth" class="form-control" />
                    <span asp-validation-for="RModel.dateOfBirth" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.Email">Email Address</label>
                    <input type="text" asp-for="RModel.Email" class="form-control" />
                    <span asp-validation-for="RModel.Email" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.Password">Password</label>
                    <input type="password" asp-for="RModel.Password" class="form-control" oninput=validatePassword() />
                    <span asp-validation-for="RModel.Password" class="text-danger"></span>
                    <div id="password-strength-indicator" class="text-muted"></div>
                    <label class="form-label" asp-for="RModel.Password" id="passwordChecker"></label>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.ConfirmPassword">Confirm Password</label>
                    <input type="password" asp-for="RModel.ConfirmPassword" class="form-control" oninput=validateConfirmPassword() />
                    <span asp-validation-for="RModel.ConfirmPassword" class="text-danger"></span>
                    <div id="password-strength-indicator" class="text-muted"></div>
                    <label class="form-label" asp-for="RModel.ConfirmPassword" id="passwordCheckercf"></label>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.whoAmI">Who Am I</label>
                    <input type="text" asp-for="RModel.whoAmI" class="form-control" />
                    <span asp-validation-for="RModel.whoAmI" class="text-danger"></span>
                </div>


                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.resume">Resume</label>
                    <input type="file" asp-for="RModel.resume" class="form-control" />
                    <span asp-validation-for="RModel.resume" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Register</button>
                </div>
            </form>
        </div>

    </div>

</div>


@section Scripts {
    <script>
        function validatePassword() {
            var str = document.getElementById("RModel_Password").value;

            if (str.length < 8) {
                document.getElementById("passwordChecker").innerHTML = "Weak";
                document.getElementById("passwordchecker").style.color = "Red"
                return ("too_short")
            }
            else if (str.search(/[A-Z]/) == -1) {
                document.getElementById("passwordChecker").innerHTML = "Need to have at least 1 capitalized letter";
                document.getElementById("passwordChecker").style.color = "Red"
                return ("no_number")
            }
            else if (str.search(/[0-9]/) == -1) {
                document.getElementById("passwordChecker").innerHTML = "Need to have at least 1 number";
                document.getElementById("passwordChecker").style.color = "Red"
                return ("no_number")
            }
            else if (str.search(/[!#$%^&*(),.?""':{}|<>]/) == -1) {
                document.getElementById("passwordChecker").innerHTML = "Need to have at least 1 special character";
                document.getElementById("passwordChecker").style.color = "Red"
                return ("no_special")
            }
            document.getElementById("passwordChecker").innerHTML = "Strong";
            document.getElementById("passwordChecker").style.color = "Blue"
        }
        function validateConfirmPassword() {
            var strcf = document.getElementById("RModel_ConfirmPassword").value;

            if (strcf.length < 8) {
                document.getElementById("passwordCheckercf").innerHTML = "Weak";
                document.getElementById("passwordCheckercf").style.color = "Red"
                return ("too_short")
            }
            else if (strcf.search(/[A-Z]/) == -1) {
                document.getElementById("passwordCheckercf").innerHTML = "Need to have at least 1 capitalized letter";
                document.getElementById("passwordCheckercf").style.color = "Red"
                return ("no_number")
            }
            else if (strcf.search(/[0-9]/) == -1) {
                document.getElementById("passwordCheckercf").innerHTML = "Need to have at least 1 number";
                document.getElementById("passwordCheckercf").style.color = "Red"
                return ("no_number")
            }
            else if (strcf.search(/[!#$%^&*(),.?""':{}|<>]/) == -1) {
                document.getElementById("passwordCheckercf").innerHTML = "Need to have at least 1 special character";
                document.getElementById("passwordCheckercf").style.color = "Red"
                return ("no_special")
            }
            document.getElementById("passwordCheckercf").innerHTML = "Strong";
            document.getElementById("passwordCheckercf").style.color = "Blue"
        }
    </script>
}

Appsec_222360C/Pages/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Appsec_222360C.Model
@inject SignInManager<ApplicationUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Appsec_222360C</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Appsec_222360C.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Appsec_222360C</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @{
                        if (SignInManager.IsSignedIn(User))
                        {
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                                </li>
                            </ul>

                            <ul class="navbar-nav d-flex justify-content-end">
                                <li class="nav-item">
                                    <a class="btn btn-primary" asp-area="" asp-page="/Logout">Logout</a>
                                </li>
                            </ul>
                        }
                        else
                        {
                            <ul class="navbar-nav d-flex justify-content-end flex-grow-1">
                                <li class="nav-item">
                                    <a class="btn btn-primary" asp-page="/Login">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="btn btn-primary" asp-page="/Register">Register</a>
                                </li>
                            </ul>
                        }
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Appsec_222360C - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>